# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sexo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('password', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_usuario', to='main.Escuela')),
                ('id_sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sexo_usuario', to='main.Sexo')),
            ],
        ),
    ]
