# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_publicacion', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('path_archivo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Publicacion')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Escuela'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sexo'),
        ),
        migrations.AddField(
            model_name='seguidores',
            name='id_seguidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_seguidor', to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='seguidores',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='publicacioncomentario',
            name='id_autor_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='publicacioncomentario',
            name='id_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Comentario'),
        ),
        migrations.AddField(
            model_name='publicacioncomentario',
            name='id_publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Publicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
    ]
