# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nickname',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
